### ISSUE TITLE
error in helper.php on line 64

### ISSUE THREAD

**Issue by cherom812** [gregorionuti/Joomla-Digi-Showcase#2] opened 2024-03-22 12:27 UTC
Hello. Modul don't work correctly, i see this error on front and in admin panel. How I fix it?

![front error](https://github.com/gregorionuti/Joomla-Digi-Showcase/assets/164503840/f0e8ad36-6ad5-4630-b0af-6c5f449b5c24)

**Comment by gregorionuti** [comment] 2024-03-25 07:49
Please, can you provide some info about your environment: Joomla version, PHP version, Apache/Nginx, Windows/Linux
As well as: Digi Showcase data source, Digi Showcase mode

**Comment by cherom812** [comment] 2024-03-25 09:17
Joomla! 4.4.3, Web Server  Apache/2.4.55 (Unix) OpenSSL/1.0.2k-fips mpm-itk/2.4.7-04 Phusion_Passenger/5.1.12 PHP/8.1.26 mod_wsgi/4.9.4 Python/3.6
Digi Showcase Data source - Joomla Categories,  Digi Showcase mode - Standard mode
I see this message right after installation Digi Showcase in admin panel (Basic option). The module Digi Showcase itself works fine, I can organize stuff with it. But this message (in front) bothers me.

**Comment by gregorionuti** [comment] 2024-03-25 13:58
It should be fixed. Can you please to try to install the patched version from https://github.com/gregorionuti/Joomla-Digi-Showcase/archive/refs/heads/main.zip and let me know if the issue is solved?

**Comment by cherom812** [comment] 2024-03-25 14:11
Problem solved! Thank you very much!

**Closed as completed** 2024-03-25 14:32 UTC
